<?php
echo "PHP VERSION = " . PHP_VERSION;
echo "<br>VERSION ID = " . PHP_VERSION_ID;
echo "<br>PHP MAJOR VERSION = " . PHP_MAJOR_VERSION;
echo "<br>MINOR VERSION = " . PHP_MINOR_VERSION;
echo "<br>RELEASE VERSION = " . PHP_RELEASE_VERSION;
?>